table users {
  id integer [pk, not null, increment]
  registered_at text
  username text
}

table posts {
  id integer [pk, not null, increment]
  posted_by_user_registered_at text
  posted_by text
}

ref posts_posted_by_posted_by_user_registered_at_users_username_registered_at_fk: posts.(posted_by, posted_by_user_registered_at) > users.(username, registered_at) [delete: no action, update: no action]