table my_table {
  pk integer [pk, not null]
  nn integer [not null]
  u integer [unique]
  default_s text [default: 'some text']
  default_n integer [default: 1]
  default_now timestamp [default: `now()`]
  default_a integer[] [default: `[1,2,3]`]
  ai serial [not null, increment]
  multiple text [not null, default: 'other text']
}