table test.users {
  id serial [pk, not null, increment]
  config_id integer
}

table test.user_config {
  id serial [pk, not null, increment]
}

table test.items {
  id serial [pk, not null, increment]
  sold_by_id integer [not null]
}

ref: test.users.config_id - test.user_config.id

ref: test.items.sold_by_id > test.users.id