name: Publish Release
on:
  release:
    types:
      - released
jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Test Postgres Dialect
        run: pnpm test:pg
      - name: Build
        run: pnpm build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}